import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage();
page.on("pageerror", (err) => console.log("ERR:", err.message));
await page.goto("http://localhost:3000/en-gb/privacy", { waitUntil: "load", timeout: 60000 });
await page.waitForSelector('button[aria-label="Toggle theme"]:not([disabled])');
console.log("theme before:", await page.evaluate(() => document.documentElement.getAttribute("data-theme")));
await page.click('button[aria-label="Toggle theme"]:not([disabled])');
await page.waitForTimeout(1000);
console.log("theme after 1st click:", await page.evaluate(() => document.documentElement.getAttribute("data-theme")));
await page.click('button[aria-label="Toggle theme"]:not([disabled])');
await page.waitForTimeout(1000);
console.log("theme after 2nd click:", await page.evaluate(() => document.documentElement.getAttribute("data-theme")));
console.log("stray .dark class:", await page.evaluate(() => document.documentElement.classList.contains("dark")));
await browser.close();
