import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(packageDirectory, "../../src/styles/base.css");
const outputPath = resolve(packageDirectory, "dist/tokens.css");
const source = await readFile(sourcePath, "utf8");
const start = source.indexOf(":root{");
const end = source.indexOf("\n*{box-sizing:border-box}");

if (start === -1 || end === -1 || end <= start) {
  throw new Error("Could not locate the light and dark token blocks in src/styles/base.css.");
}

const banner = [
  "/* DOMINIC Portfolio design tokens — generated from src/styles/base.css.",
  " * Do not edit this file directly; update the source tokens and rebuild. */",
].join("\n");

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, `${banner}\n${source.slice(start, end).trim()}\n`, "utf8");

console.log(`Built ${outputPath}`);
