// Extracts only the icons used by src/data/core-tech.ts, contact.ts and social.ts into a small offline module of
// ready-to-render SVG data, so icons are in the server HTML, nothing is fetched from
// the Iconify API, and whole icon sets never reach the bundle.
// Fails loudly if any icon id doesn't exist. Run: npm run icons
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { getIconData, iconToSVG } from '@iconify/utils';
import { coreTechGroups } from '../src/data/core-tech.ts';
import { contactInfo } from '../src/data/contact.ts';
import { socialLinks } from '../src/data/social.ts';

const require = createRequire(import.meta.url);
const sets: Record<string, any> = {
  'simple-icons': require('@iconify-json/simple-icons/icons.json'),
  tabler: require('@iconify-json/tabler/icons.json'),
  logos: require('@iconify-json/logos/icons.json'),
};

const out: Record<string, { viewBox: string; body: string }> = {};
const missing: string[] = [];
const coreTech = coreTechGroups.flatMap((g) => g.items);
for (const { icon } of [...coreTech, ...contactInfo, ...socialLinks]) {
  if (out[icon]) continue;
  const [prefix, name] = icon.split(':');
  const set = sets[prefix];
  const data = set && getIconData(set, name);
  if (!data) { missing.push(icon); continue; }
  const svg = iconToSVG({ ...data, width: data.width ?? set.width ?? 16, height: data.height ?? set.height ?? 16 });
  out[icon] = { viewBox: svg.attributes.viewBox, body: svg.body };
}
if (missing.length) {
  console.error(`Unknown icon id(s): ${missing.join(', ')}`);
  process.exit(1);
}

writeFileSync(
  new URL('../src/data/stack-icons.ts', import.meta.url),
  `// Generated by scripts/generate-stack-icons.mts. Do not edit by hand.\n` +
    `export type StackIconData = { viewBox: string; body: string };\n\n` +
    `export const stackIcons: Record<string, StackIconData> = ${JSON.stringify(out, null, 2)};\n`,
);
console.log(`Wrote ${Object.keys(out).length} icons for ${coreTech.length} core-tech and ${contactInfo.length} contact items.`);
